snippets:
  - name: git status
    keyword: gs
    snippet: git status --short --branch
  - name: git commit message
    keyword: gcim
    snippet: git commit -m '{{commit_message}}'
  - name: git push
    keyword: gp
    snippet: git push
  - name: dotnet build
    keyword: db
    snippet: dotnet build --nologo --no-restore
  - name: ghq cd
    keyword: gcd
    snippet: cd "$(ghq list --full-path '{{query}}'| fzf)"
  - name: dotnet test
    keyword: dt
    snippet: dotnet test --nologo --no-restore
  - name: chezmoi edit
    keyword: ced
    snippet: chezmoi edit
  - name: chezmoi cd
    keyword: ccd
    snippet: chezmoi cd

completions:
  - name: dotnet add reference
    patterns:
      - "^dotnet add reference $"
    sourceCommand: "fd . -e csproj --full-path \"$(git rev-parse --show-toplevel)\""
    options:
      --prompt: "'Find csproj > '"
  - name: kill
    patterns:
      - "^kill( -9)? $"
    sourceCommand: "procs --color=always"
    options:
      --multi: true
      --prompt: "'Kill Process > '"
    callback: "awk '{print $1}'"
