# 特に使ってないけど、fzf-preview.vimの依存として入れてる
[[plugins]]
repo = 'neoclide/coc.nvim'
if = "executable('node')"
on_cmd = 'CocCommand'
rev = 'release'
hook_add = '''
  let g:coc_global_extensions = [
        \ 'coc-fzf-preview',
        \ ]
  let g:coc_data_home = $'{stdpath('data')}/coc'
  " 補完を無効化する
  autocmd VimRc User CocNvimInit ++once CocDisable
'''
