hook_add = '''
  " Vimが起動するとき、 $COLOR_SCHEMEでカラースキームが指定されていればそれを設定する。
  " $COLOR_SCHEMEが指定されていなかったとき、`g:themeSetups`に登録されているカラースキームから無作為に設定する
  " 直下で定義しているautocmdも実行させたいのでnestedを指定する
  autocmd VimRc VimEnter * ++once ++nested
        \ execute 'colorscheme' $COLOR_SCHEME
        \ ?? { items -> items[rand(srand()) % items->len()] }(g:themeSetups->keys())
  " カラースキームが設定されたとき、`g:themeSetups`に名前が登録されていれば実行する。
  " OptionSet background のautocmdを実行したいのでnestedを指定する
  autocmd VimRc ColorSchemePre * ++nested
        \ :if has_key(g:themeSetups, expand('<amatch>'))
        \ |  call g:themeSetups[expand('<amatch>')]()
        \ |endif
'''

[[plugins]]
repo = 'rose-pine/neovim'
name = 'rose-pine'
hook_add = '''
  " NOTE:
  " よくわからないけどファイル先頭のhook_addより先にこっちが実行されるっぽいので
  " ここで`g:themeSetups`を宣言しないとエラーになる
  let g:themeSetups = get(g:, 'themeSetups', {})
  let g:themeSetups['rose-pine'] = { -> luaeval('require("rc.colorscheme-setups.rose-pine")') }
'''

[[plugins]]
repo = 'rebelot/kanagawa.nvim'
hook_add = '''
  let g:themeSetups['kanagawa'] = { -> luaeval('require("rc.colorscheme-setups.kanagawa")') }
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  let g:themeSetups['iceberg'] = { -> luaeval('require("rc.colorscheme-setups.iceberg")') }
'''

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
  let g:themeSetups['gruvbox-material'] = { -> luaeval('require("rc.colorscheme-setups.gruvbox-material")') }
'''

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
  let g:themeSetups['edge'] = { -> luaeval('require("rc.colorscheme-setups.edge")') }
'''

[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
  let g:themeSetups['everforest'] = { -> luaeval('require("rc.colorscheme-setups.everforest")') }
'''

[[plugins]]
repo = 'sainnhe/sonokai'
hook_add = '''
  let g:themeSetups['sonokai'] = { -> luaeval('require("rc.colorscheme-setups.sonokai")') }
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
hook_add = '''
  let g:themeSetups.nightfox  = {->v:null}
  let g:themeSetups.duskfox   = {->v:null}
  let g:themeSetups.dawnfox   = {->v:null}
  let g:themeSetups.nordfox   = {->v:null}
  let g:themeSetups.dayfox    = {->v:null}
  let g:themeSetups.terafox   = {->v:null}
  let g:themeSetups.carbonfox = {->v:null}
'''

[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
  let g:themeSetups['tokyonight-night'] = { -> luaeval('require("rc.colorscheme-setups.tokyonight")') }
'''

[[plugins]]
repo = 'YorickPeterse/vim-paper'
hook_add = '''
  let g:themeSetups.paper = {->v:null}
'''

[[plugins]]
repo = 'shaunsingh/nord.nvim'
hook_add = '''
  let g:themeSetups['nord'] = { -> luaeval('require("rc.colorscheme-setups.nord")') }
'''

[[plugins]]
repo = 'Julpikar/night-owl.nvim'
hook_add = '''
  let g:themeSetups['night-owl'] = {->v:null}
'''

[[plugins]]
repo = 'catppuccin/nvim'
name = 'catppuccin'
hook_add = '''
  let g:themeSetups['catppuccin-latte'] = { -> luaeval('require("rc.colorscheme-setups.catppuccin")') }
  let g:themeSetups['catppuccin-frappe'] = { -> luaeval('require("rc.colorscheme-setups.catppuccin")') }
  let g:themeSetups['catppuccin-macchiato'] = { -> luaeval('require("rc.colorscheme-setups.catppuccin")') }
  let g:themeSetups['catppuccin-mocha'] = { -> luaeval('require("rc.colorscheme-setups.catppuccin")') }
'''

[[plugins]]
repo = 'machakann/vim-colorscheme-snowtrek'
hook_add = '''
  let g:themeSetups.snowtrek = {->v:null}
'''

[[plugins]]
repo = 'eihigh/vim-aomi-grayscale'
hook_add = '''
  let g:themeSetups['aomi-grayscale'] = { -> luaeval('require("rc.colorscheme-setups.aomi-grayscale")') }
'''

[[plugins]]
repo = 'marko-cerovac/material.nvim'
hook_add = '''
  let g:themeSetups.material = {->v:null}
'''
