# skkeletonの補完メニューを提供してもらってる
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = 'denops.vim'
hook_add = '''
  lua require 'rc.plugin-setups.ddc'
'''

# ddc.vimの補完メニューとしてpum.vimを使うためのやつ
[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = 'pum.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-native'

# Shougo先生による補完メニューの実装
[[plugins]]
repo = 'Shougo/pum.vim'
# キーマップはnvim-cmpで解決するのでここでは設定しない
hook_add = '''
  " なんかのプラグインがpum.vimを呼び出したときに実行する
  " Vimの初期化より先に実行したい処理ではないため
  autocmd VimRc SourcePost pum.vim ++once call pum#set_option('border', 'rounded')
'''

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'matsui54/ddc-buffer'

[[plugins]]
repo = 'Shougo/neco-vim'
