[[plugins]]
repo = 'Shougo/ddu.vim'
hook_add = '''
  nnoremap <space>b <Plug>(ddu-buffers)

  " なんかのマッピングが実行されるまでautoload/ddu.vimを読み込まないようにする
  " 初回実行時に待機時間が発生するので微妙かも
  nnoremap <Plug>(ddu- :<C-u>execute 'nunmap' '<Plug>(ddu-'<CR><Cmd>lua require('rc.ddu').setup()<CR><Plug>(ddu-

  autocmd VimRc VimEnter * ++once call timer_start(10, { -> ddu#start({}) })
'''

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
