[ftplugin]
cs = '''
  compiler dotnet
  setl indentkeys-=<>>
  setl colorcolumn=130
'''
razor = '''
  compiler dotnet
  setl colorcolumn=130
'''

[[plugins]]
repo = 'jlcrochet/vim-razor'

[[plugins]]
repo = 'PhilT/vim-fsharp'

[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = 'csv'
hook_add = '''
  let g:csv_default_delim = ','
'''

[[plugins]]
repo = 'wgwoods/vim-systemd-syntax'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
