[[plugins]]
repo = 'junegunn/fzf'
lazy = true
merged = false
build = 'go install'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
on_func = 'fzf#'
on_cmd = ['FzfPlugins', 'GhqFind']
hook_add = '''
  let g:fzf_command_prefix = 'Fzf'
  call add(g:AlterCommands, #{ char: 'fp', input: 'FzfPlugins' })
  call add(g:AlterCommands, #{ char: 'fq', input: 'GhqFind' })
'''
hooks_file = '$DEIN_CONFIG_DIR/fzf.vim.lua'

[[plugins]]
repo = 'ibhagwan/fzf-lua'
if = "executable('fzf')"
depends = ['nvim-web-devicons', 'nvim-treesitter']
on_lua = 'fzf-lua'
on_cmd = 'FzfLua'
hooks_file = '$DEIN_CONFIG_DIR/fzf-lua.lua'
