[[plugins]]
repo = 'junegunn/fzf'
lazy = true
merged = false
build = 'go install'
hook_add = '''
  " NOTE: なんかこれ実行するとfzf.vimが読み込まれるんだけど理由はよくわからない
  lua << EOF
  vim.api.nvim_create_user_command(
    'FzfPlugins',
    function(args)
      vim.fn['fzf#run'] {
        source = vim.fn.map(
          vim.fn.values(vim.fn['dein#get']()),
          function(_, plugin)
            return plugin.name
          end),
        sink = function(name)
          require('fzf-lua').files {
            cwd = vim.fn['dein#get'](name).path
          }
        end,
        window = {
          width = 0.9,
          height = 0.6,
        },
      }
    end,
    {}
  )
EOF
  nmap <space>fp <Cmd>FzfPlugins<CR>

  command FzfMrw call fzf#run(#{
        \ source: mr#mrw#list(),
        \ sink: 'edit',
        \ window: #{
        \   width: 0.9,
        \   height: 0.6,
        \ },
        \ })
  nmap <space>fz <Cmd>FzfMrw<CR>

  lua << EOF
  vim.api.nvim_create_user_command(
    'GhqFind',
    function(args)
      vim.fn['fzf#run'] {
        source = vim.fn.systemlist { 'ghq', 'list', '--full-path' },
        sink = function(path)
          require('fzf-lua').files {
            cwd = path
          }
        end,
        window = {
          width = 0.9,
          height = 0.6,
        }
      }
    end,
    {}
  )
EOF
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
lazy = true
depends = 'fzf'
hook_add = '''
  let g:fzf_command_prefix = 'Fzf'
'''

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
lazy = true
if = "executable('node')"
depends = ['fzf.vim', 'coc.nvim']
on_cmd = [
  'FzfPreviewGitActions',
  'FzfPreviewMruFiles',
  'FzfPreviewProjectMruFiles',
  'FzfPreviewProjectFiles',
]
hook_add = '''
  nmap <space>af <Cmd>FzfPreviewGitActions<CR>
'''

[[plugins]]
repo = 'ibhagwan/fzf-lua'
lazy = true
if = "executable('fzf')"
depends = ['nvim-web-devicons', 'nvim-treesitter']
on_lua = 'fzf-lua'
on_cmd = 'FzfLua'
lua_add = '''
  vim.keymap.set('n', '<Plug>(ff-files)', '<Cmd>FzfLua files<CR>')
  vim.keymap.set('n', '<Plug>(ff-config_files)', function()
    require('fzf-lua').files {
      cwd = ('%s/chezmoi'):format(vim.env.XDG_DATA_HOME)
    }
  end)
  vim.keymap.set('n', '<Plug>(ff-grep)', '<Cmd>FzfLua grep<CR>')
  vim.keymap.set('n', '<Plug>(ff-help_tags)', '<Cmd>FzfLua help_tags<CR>')
  vim.keymap.set('n', '<Plug>(ff-buffers)', '<Cmd>FzfLua buffers<CR>')
  vim.keymap.set('n', '<Plug>(ff-buffers)', '<Cmd>FzfLua buffers<CR>')
  vim.keymap.set('n', '<Plug>(ff-lines)', '<Cmd>FzfLua lines<CR>')
  vim.keymap.set('n', '<Plug>(ff-resume)', '<Cmd>FzfLua resume<CR>')
  vim.keymap.set('n', '<Plug>(ff-lsp_references)', '<Cmd>FzfLua lsp_references<CR>')
  vim.keymap.set('n', '<Plug>(ff-lsp_implementations)', '<Cmd>FzfLua lsp_implementations<CR>')
'''
hooks_file = '$DEIN_CONFIG_DIR/fzf-lua.lua'
