# neovim用の自動補完エンジン
# マッピングを処理する機能が強力なのでddcでは代替できない
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depends = ['vim-vsnip', 'lspkind-nvim']
on_event = ['InsertEnter', 'CmdlineEnter']
hooks_file = '$DEIN_CONFIG_DIR/nvim-cmp.lua'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
depends = 'nvim-cmp'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
on_source = 'nvim-cmp'

[[plugins]]
repo  = 'hrsh7th/cmp-emoji'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'f3fora/cmp-spell'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
depends = 'vim-vsnip'
on_source = 'nvim-cmp'
