[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ['InsertEnter', 'CmdlineEnter']
hooks_file = '$DEIN_CONFIG_DIR/lexima.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
on_map = { i = '<Plug>(emmet-' }
hook_add = '''
  imap <C-y>, <Plug>(emmet-expand-abbr)
  imap <C-y>; <Plug>(emmet-expand-word)
  imap <C-y>u <Plug>(emmet-update-tag)
  imap <C-y>d <Plug>(emmet-balance-tag-inward)
  imap <C-y>D <Plug>(emmet-balance-tag-outward)
  imap <C-y>n <Plug>(emmet-move-next)
  imap <C-y>N <Plug>(emmet-move-prev)
  imap <C-y>i <Plug>(emmet-image-size)
  imap <C-y>/ <Plug>(emmet-toggle-comment)
  imap <C-y>j <Plug>(emmet-split-join-tag)
  imap <C-y>k <Plug>(emmet-remove-tag)
  imap <C-y>a <Plug>(emmet-anchorize-url)
  imap <C-y>A <Plug>(emmet-anchorize-summary)
  imap <C-y>m <Plug>(emmet-merge-lines)
  imap <C-y>c <Plug>(emmet-code-pretty)
'''

[[plugins]]
repo = 'mattn/vim-sonictemplate'
merge_ftdetect = true
on_ft = 'stpl'
on_cmd = 'Template'
hook_add = '''
  let g:sonictemplate_vim_template_dir = [$'{stdpath("config")}/template']
'''
hooks_file = '$DEIN_CONFIG_DIR/vim-sonictemplate.vim'
[plugins.ftplugin]
stpl = '''
  setl tabstop=4
  setl noexpandtab
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_func = 'vsnip#'
hook_add = '''
  let g:vsnip_snippet_dir = $'{stdpath('config')}/vsnip'
  let g:vsnip_filetypes = #{
        \ javascriptreact: ['javascript'],
        \ typescriptreact: ['typescript'],
        \ }
'''
